export const COMPLETION_DELAY_MS = 650;
export const WRITE_SEARCH_DEBOUNCE_MS = 250;
export const COMPLETION_MIN_TRAILING_CHARS = 10;
export const WRITE_COMPLETION_PREFIX_MAX_CHARS = 4096;
export const WRITE_COMPLETION_SUFFIX_MAX_CHARS = 1024;
export const WRITE_ASSISTANT_CONTEXT_MAX_CHARS = 1200;
export const WRITE_ASSISTANT_NEARBY_CONTEXT_RADIUS = 520;
